DjangoApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jboard.urls')),
]

jboard/urls.py
from django.urls import path
from .views import HomeView,DailyView,MacroView,PFBondsCreateView
from . import views

app_name='jboard'

urlpatterns=[
    path('',views.HomeView.as_view(),name='home'),
    #path('datainput/',views.datainput,name='datainput'),
    path('daily/',views.DailyView.as_view(),name='daily'),
    path('macro/',views.MacroView.as_view(),name='macro'),
    path('portfolio/',views.portfolio,name='portfolio'),

    path('portfolio/create_pf_stocks/',views.PFKStocksCreateView.as_view(),name='create_pf_stocks'),
    path('portfolio/create_pf_bonds/',views.PFBondsCreateView.as_view(),name='create_pf_bonds'),
        
]

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>AlphaPan</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'jboard:home' %}">AlphaPan</a>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'jboard:daily' %}">Daily</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'jboard:macro' %}">Macro</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'jboard:portfolio' %}">Protfolio</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
</body>
</html>